version: '3'

networks:
  inception:
      driver: bridge
volumes:
  data:
    driver_opts:
      type: "bind"
      o: "bind"
      device: "/home/akhouya/data/mysql"
  wordpress:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/akhouya/data/wordpress"
  portainer:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/akhouya/data/portainer"
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    init : true
    networks:
      - inception
    volumes:
      - wordpress:/wordpress
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build: 
      context : requirements/mariadb
      args:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DB
      - MYSQL_HOST
      - DB_ROOT_PASSWORD
    restart: 'always'
    volumes: 
      - data:/var/lib/mysql/
    networks:
        - inception
    init: true
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    env_file:
      - .env
    restart: unless-stopped
    init : true
    # ports:
    #   - 9000:9000
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/wordpress

  redis:
    build: requirements/bonus/redis/
    container_name: redis
    env_file:
      - .env
    restart: unless-stopped
    init : true
    networks:
      - inception
    depends_on:
      - wordpress

  ftp:
    build: requirements/bonus/ftp/
    container_name: ftp
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 21:21
      - "40000-40009:40000-40009"
    init : true
    networks:
      - inception
    volumes:
      - wordpress:/home/akhouya42/ftp_directory/wordpress
    depends_on:
      - wordpress
    
  adminer:
    build: requirements/bonus/adminer/
    container_name: adminer
    env_file:
      - .env
    restart: unless-stopped
    init : true
    networks:
      - inception
  portfolio:
    build: requirements/bonus/portfolio/
    container_name: portfolio
    env_file:
      - .env
    restart: unless-stopped
    init : true
    networks:
      - inception
  portainer:
    build: requirements/bonus/portainer/
    container_name: portainer
    image : portainer
    restart: 'always'
    init : true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - inception
